In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [11]:
class KaiYue(nn.Module):
    def __init__(self):
        super(KaiYue,self).__init__()
    def forward(self,x):
        y=x+1
        return y

In [13]:
kaiyue=KaiYue()
x=torch.tensor(1.0)
y=kaiyue(x)
print(y)

tensor(2.)


#   卷积的运算

In [17]:
#生成一个5*5的整数数据
input=torch.randint(1,10,(5,5))
kernel=torch.randint(1,10,(3,3))

input=torch.reshape(input,(1,1,5,5))
kernel=torch.reshape(kernel,(1,1,3,3))
output1=F.conv2d(input,kernel,stride=1,padding=0)
print(output1)

output2=F.conv2d(input,kernel,stride=2,padding=0)
print(output2)

output3=F.conv2d(input,kernel,stride=1,padding=1)
print(output3)


tensor([[[[187, 132, 215],
          [175, 151, 182],
          [165, 174, 150]]]])
tensor([[[[187, 215],
          [165, 150]]]])
tensor([[[[ 63, 164, 128, 175,  91],
          [ 86, 187, 132, 215, 101],
          [ 95, 175, 151, 182,  69],
          [117, 165, 174, 150,  84],
          [ 73,  95, 103,  70,  44]]]])
